// This file was autogenerated using @guardian/cdk-cli

import "@aws-cdk/assert/jest";
import { SynthUtils } from "@aws-cdk/assert";
import { App } from "@aws-cdk/core";
import { CdkPlayground } from "./cdk-playground";

describe("The Deploy stack", () => {
  it("matches the snapshot", () => {
    const app = new App();
    const stack = new CdkPlayground(app, "CdkPlayground", { stack: "deploy" });
    expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
  });
});
