#!/usr/bin/env bash

set -e

(
  cd cdk
  npm ci
  npm run lint
  npm run test
  npm run synth
)

(
  cd lambda
  zip cdk-playground-lambda.zip handler.js
  zip cdk-playground-lambda-test.zip handler.js
)

sbt clean compile test debian:packageBin

# `sbt debian:packageBin` produces `target/cdk-playground_1.0-SNAPSHOT_all.deb`. Rename it to something easier.
mv target/cdk-playground_1.0-SNAPSHOT_all.deb target/cdk-playground.deb
