#!/usr/bin/env bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DIR=$DIR/..

setupNvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

  nvm install
  nvm use
}

synthCdk() {
  setupNvm

  pushd $ROOT_DIR/cdk

  npm install -g yarn

  yarn install
  yarn lint
  yarn test
  yarn synth

  popd
}

synthCdk
sbt clean compile test riffRaffNotifyTeamcity
