#!/usr/bin/env bash

set -e

if [[ ! -z "${TEAMCITY_VERSION}" ]]; then
  echo "Running in TeamCity. Don't build anything!"
  exit 0
fi

(
  cd cdk
  npm ci
  npm run lint
  npm run test
  npm run synth
)

sbt clean compile test riffRaffUpload
