#!/usr/bin/env bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DIR=$DIR/..

if [[ $# -lt 1 ]]
then
  echo "Usage: $0 <branch name>"
  echo "Want to switch to using NPM? Either revert changes to cdk/package.json or install latest with:"
  echo "  npm i @guardian/cdk@latest"
	exit 1
fi

BRANCH=$1

(
  cd $ROOT_DIR/cdk
  npm i "guardian/cdk#${BRANCH}"
)
