name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: guardian/cdk@aa-composite-action
      - uses: guardian/sbt-riffraff-artifact@aa-composite-action
        with:
          riffRaffRoleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
