name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  facts:
    runs-on: ubuntu-slim
    permissions: {} # This job doesn't need any permissions. Explicitly set it to an empty object to avoid inheriting any default permissions of the workflow.
    outputs:
      branchName: ${{ steps.get-build-facts.outputs.branchName }}
      buildNumber: ${{ steps.get-build-facts.outputs.buildNumber }}
      commitSha: ${{ steps.get-build-facts.outputs.commitSha }}
      buildTime: ${{ steps.build-time.outputs.buildTime }}
    steps:
      - name: Build time
        id: build-time
        shell: bash
        run: echo "buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"
      - uses: guardian/actions-build-facts@v0.0.1
        id: get-build-facts

  ci-image:
    runs-on: ubuntu-latest
    needs: [facts]
    permissions:
      contents: read
      id-token: write # Required to exchange for AWS credentials using OIDC
    outputs:
      imageDigest: ${{ steps.publish-image.outputs.imageDigest }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: guardian/setup-scala@v1
      - name: Build Docker image
        env:
          COMMIT_SHA: ${{ needs.facts.outputs.commitSha }}
          BUILD_NUMBER: ${{ needs.facts.outputs.buildNumber }}
          BRANCH_NAME: ${{ needs.facts.outputs.branchName }}
          BUILD_TIME: ${{ needs.facts.outputs.buildTime }}
        run: sbt Docker/publishLocal
      - name: Normalise Docker image name
        run: docker image tag cdk-playground:1.0-SNAPSHOT ${{ github.repository }}:latest
      - name: Publish Image
        uses: guardian/actions-publish-image@v0.0.2
        id: publish-image
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          branchName: ${{ needs.facts.outputs.branchName }}
          buildNumber: ${{ needs.facts.outputs.buildNumber }}
          commitSha: ${{ needs.facts.outputs.commitSha }}
  CI:
    runs-on: ubuntu-latest
    needs:
      - facts
      - ci-image
    permissions:
      contents: read

      # These permissions are required by guardian/actions-riff-raff...
      id-token: write # ...to exchange an OIDC JWT ID token for AWS credentials
      pull-requests: write #...to comment on PRs

    steps:
      # Checkout the branch
      - uses: actions/checkout@v7.0.0

      # Node is needed for CDK
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.tool-versions'
          cache: npm
          cache-dependency-path: 'cdk/package-lock.json'

      - uses: guardian/setup-scala@v1

      # Build CDK and Play (in sequence)
      - run: ./script/ci
        env:
          COMMIT_SHA: ${{ needs.facts.outputs.commitSha }}
          BUILD_NUMBER: ${{ needs.facts.outputs.buildNumber }}
          BRANCH_NAME: ${{ needs.facts.outputs.branchName }}
          BUILD_TIME: ${{ needs.facts.outputs.buildTime }}
          IMAGE_DIGEST: ${{ needs.ci-image.outputs.imageDigest }}

      # Upload our build artifacts to Riff-Raff (well, S3)
      - uses: guardian/actions-riff-raff@v4
        with:
          projectName: devx::cdk-playground
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: cdk/cdk.out/devx::cdk-playground/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            cdk-playground:
              - dist/cdk-playground
            cdk-playground-lambda:
              - lambda/cdk-playground-lambda.zip
            event-forwarder:
              - cdk/dist/event-forwarder.zip
