name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest

    permissions:
      contents: read

      # These permissions are required by guardian/actions-riff-raff...
      id-token: write # ...to exchange an OIDC JWT ID token for AWS credentials
      pull-requests: write #...to comment on PRs

    steps:
      # Checkout the branch
      - uses: actions/checkout@v5

      # Node is needed for CDK
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: 'cdk/package-lock.json'

      - uses: guardian/setup-scala@v1

      # Build CDK and Play (in sequence)
      - run: ./script/ci

      # Upload our build artifacts to Riff-Raff (well, S3)
      - uses: guardian/actions-riff-raff@v4
        with:
          projectName: devx::cdk-playground
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            cdk-playground:
              - dist/cdk-playground
            cdk-playground-lambda:
              - lambda/cdk-playground-lambda.zip
            event-forwarder:
              - cdk/dist/event-forwarder.zip
