# In this project, CI passing is a strong enough signal that the PR is safe to merge

name: Dependabot auto-approve
on: pull_request

permissions:
  # Dependabot requires those who comment "@dependabot merge" have push access to the repository:
  # > Sorry, only users with push access can use that command.
  contents: write

  # Allow commenting on PRs
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve a PR
        run: gh pr review --approve --body "@dependabot merge" "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
