name: Simple Snyk monitor container images
#Todo make this run only after publish.yml has run

on:
    push:
        branches:
            - main
            - docker

    workflow_dispatch:
    workflow_call:

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - uses: snyk/actions/setup@0.3.0

            - name: Snyk monitor
              run: |
                projectTags="commit=${GITHUB_SHA}"

                snyk container monitor ghcr.io/guardian/cdk-playground:docker \
                  --org="guardian-test" \
                  -d \
                  --project-tags=${projectTags} --
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}